### ISSUE TITLE
2 detected viruses

### ISSUE THREAD

**Issue by ik4reem** [PeterPePem/RiseCrack#4]
![image](https://user-images.githubusercontent.com/70220156/228817270-5ae6b235-1623-49f7-bf74-30c60ac836b7.png)
you said no virus or rat huh? well whats that?

**Comment by shisirkha** [comment]
bro its a modification for bypass
  
but if you see torjan then warn the owner

**Comment by mikusgszyp** [comment]
2 virustotal detections bruh 💀
